[gnn_features_dim]
# output dimension of feature extractor
values = [32, 64, 128, 256]

[gnn_hidden_dim]
# output dimension of Graph convolutional layer
# network hidden dimension,
#  if smaller than features_dim than the network will set features_dim=hidden_dim*2 (due to pooling)
values = [32, 64, 128, 256]

[gnn_dropout_p]
# dropout probability after convolutional layer
values=[0.01, 0.05, 0.1, 0.15, 0.2, 0.3]

[gamma]
# discount rate
low=0.9
high=0.999
log=true

[safe_max_rho]
# thermal limit over which actions are taken to prevent blackout
low=0.9
high=0.999
log=true

[n_steps]
# the number of steps to run per environment
# very low as in https://arxiv.org/pdf/2207.10330
values = [8, 16, 32, 64, 128]

[batch_size]
# minibatch size
# batch_size is min(sampled_batch_size, sampled_n_steps)
values = [8, 16, 32]

[learning_rate]
# optimization step size
low=1e-6
high=1e-5
log=true

