[net_arch]
# number of neurons in all three MLP layers
# if 200 is drawn then net_arch will be [200, 200, 200]
values = [100, 200, 300, 400, 500]
repeat = 3

[gamma]
# discount rate
low=0.9
high=0.999
log=true

[safe_max_rho]
# thermal limit over which actions are taken to prevent blackout
low=0.9
high=0.999
log=true

[n_steps]
# the number of steps to run per environment
# very low as in https://arxiv.org/pdf/2207.10330
values = [8, 16, 32, 64, 128]

[batch_size]
# minibatch size
# batch_size is min(sampled_batch_size, sampled_n_steps)
values = [8, 16, 32]

[learning_rate]
# optimization step size
low=1e-6
high=1e-5
log=true

